/*
 * generated by Xtext 2.39.0.M1
 */
package org.farhan.dsl.sheepdog.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import sheepdogxtextplugin.ui.internal.SheepdogxtextpluginActivator;

public class SheepDogUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SheepdogxtextpluginActivator.getInstance().getInjector("org.farhan.dsl.sheepdog.SheepDog");
	}

}
