/**
 * generated by Xtext 2.38.0
 */
package org.farhan.dsl.cucumber.cucumber;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.farhan.dsl.cucumber.cucumber.CucumberFactory
 * @model kind="package"
 * @generated
 */
public interface CucumberPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cucumber";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.farhan.org/dsl/cucumber/Cucumber";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cucumber";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CucumberPackage eINSTANCE = org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl.init();

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.ModelImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StepObjectImpl <em>Step Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.StepObjectImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStepObject()
   * @generated
   */
  int STEP_OBJECT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_OBJECT__NAME = MODEL__NAME;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_OBJECT__STATEMENTS = MODEL__STATEMENTS;

  /**
   * The feature id for the '<em><b>Step Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_OBJECT__STEP_DEFINITIONS = MODEL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Step Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_OBJECT_FEATURE_COUNT = MODEL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StepDefinitionImpl <em>Step Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.StepDefinitionImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStepDefinition()
   * @generated
   */
  int STEP_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_DEFINITION__STATEMENTS = 1;

  /**
   * The feature id for the '<em><b>Step Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_DEFINITION__STEP_PARAMETERS = 2;

  /**
   * The number of structural features of the '<em>Step Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StepParametersImpl <em>Step Parameters</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.StepParametersImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStepParameters()
   * @generated
   */
  int STEP_PARAMETERS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_PARAMETERS__NAME = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_PARAMETERS__STATEMENTS = 1;

  /**
   * The feature id for the '<em><b>Parameters Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_PARAMETERS__PARAMETERS_TABLE = 2;

  /**
   * The number of structural features of the '<em>Step Parameters</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_PARAMETERS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ParametersTableImpl <em>Parameters Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.ParametersTableImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getParametersTable()
   * @generated
   */
  int PARAMETERS_TABLE = 4;

  /**
   * The feature id for the '<em><b>Rows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETERS_TABLE__ROWS = 0;

  /**
   * The number of structural features of the '<em>Parameters Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETERS_TABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.FeatureImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__NAME = MODEL__NAME;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__STATEMENTS = MODEL__STATEMENTS;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__TAGS = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Abstract Scenarios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__ABSTRACT_SCENARIOS = MODEL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = MODEL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.AbstractScenarioImpl <em>Abstract Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.AbstractScenarioImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getAbstractScenario()
   * @generated
   */
  int ABSTRACT_SCENARIO = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_SCENARIO__NAME = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_SCENARIO__STATEMENTS = 1;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_SCENARIO__STEPS = 2;

  /**
   * The number of structural features of the '<em>Abstract Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_SCENARIO_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.BackgroundImpl <em>Background</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.BackgroundImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getBackground()
   * @generated
   */
  int BACKGROUND = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND__NAME = ABSTRACT_SCENARIO__NAME;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND__STATEMENTS = ABSTRACT_SCENARIO__STATEMENTS;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND__STEPS = ABSTRACT_SCENARIO__STEPS;

  /**
   * The number of structural features of the '<em>Background</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND_FEATURE_COUNT = ABSTRACT_SCENARIO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ScenarioImpl <em>Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.ScenarioImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getScenario()
   * @generated
   */
  int SCENARIO = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__NAME = ABSTRACT_SCENARIO__NAME;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__STATEMENTS = ABSTRACT_SCENARIO__STATEMENTS;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__STEPS = ABSTRACT_SCENARIO__STEPS;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__TAGS = ABSTRACT_SCENARIO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_FEATURE_COUNT = ABSTRACT_SCENARIO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ScenarioOutlineImpl <em>Scenario Outline</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.ScenarioOutlineImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getScenarioOutline()
   * @generated
   */
  int SCENARIO_OUTLINE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE__NAME = ABSTRACT_SCENARIO__NAME;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE__STATEMENTS = ABSTRACT_SCENARIO__STATEMENTS;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE__STEPS = ABSTRACT_SCENARIO__STEPS;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE__TAGS = ABSTRACT_SCENARIO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Examples</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE__EXAMPLES = ABSTRACT_SCENARIO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Scenario Outline</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE_FEATURE_COUNT = ABSTRACT_SCENARIO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ExamplesImpl <em>Examples</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.ExamplesImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getExamples()
   * @generated
   */
  int EXAMPLES = 10;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLES__TAGS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLES__NAME = 1;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLES__STATEMENTS = 2;

  /**
   * The feature id for the '<em><b>The Examples Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLES__THE_EXAMPLES_TABLE = 3;

  /**
   * The number of structural features of the '<em>Examples</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLES_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ExamplesTableImpl <em>Examples Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.ExamplesTableImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getExamplesTable()
   * @generated
   */
  int EXAMPLES_TABLE = 11;

  /**
   * The feature id for the '<em><b>Rows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLES_TABLE__ROWS = 0;

  /**
   * The number of structural features of the '<em>Examples Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLES_TABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StepTableImpl <em>Step Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.StepTableImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStepTable()
   * @generated
   */
  int STEP_TABLE = 12;

  /**
   * The feature id for the '<em><b>Rows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_TABLE__ROWS = 0;

  /**
   * The number of structural features of the '<em>Step Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_TABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.RowImpl <em>Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.RowImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getRow()
   * @generated
   */
  int ROW = 13;

  /**
   * The feature id for the '<em><b>Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__CELLS = 0;

  /**
   * The number of structural features of the '<em>Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.CellImpl <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.CellImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getCell()
   * @generated
   */
  int CELL = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__NAME = 0;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StepImpl <em>Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.StepImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStep()
   * @generated
   */
  int STEP = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__NAME = 0;

  /**
   * The feature id for the '<em><b>The Step Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__THE_STEP_TABLE = 1;

  /**
   * The feature id for the '<em><b>The Doc String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__THE_DOC_STRING = 2;

  /**
   * The number of structural features of the '<em>Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.DocStringImpl <em>Doc String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.DocStringImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getDocString()
   * @generated
   */
  int DOC_STRING = 16;

  /**
   * The feature id for the '<em><b>Lines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOC_STRING__LINES = 0;

  /**
   * The number of structural features of the '<em>Doc String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOC_STRING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.GivenImpl <em>Given</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.GivenImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getGiven()
   * @generated
   */
  int GIVEN = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__NAME = STEP__NAME;

  /**
   * The feature id for the '<em><b>The Step Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__THE_STEP_TABLE = STEP__THE_STEP_TABLE;

  /**
   * The feature id for the '<em><b>The Doc String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__THE_DOC_STRING = STEP__THE_DOC_STRING;

  /**
   * The number of structural features of the '<em>Given</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN_FEATURE_COUNT = STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.WhenImpl <em>When</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.WhenImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getWhen()
   * @generated
   */
  int WHEN = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__NAME = STEP__NAME;

  /**
   * The feature id for the '<em><b>The Step Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__THE_STEP_TABLE = STEP__THE_STEP_TABLE;

  /**
   * The feature id for the '<em><b>The Doc String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__THE_DOC_STRING = STEP__THE_DOC_STRING;

  /**
   * The number of structural features of the '<em>When</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN_FEATURE_COUNT = STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ThenImpl <em>Then</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.ThenImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getThen()
   * @generated
   */
  int THEN = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__NAME = STEP__NAME;

  /**
   * The feature id for the '<em><b>The Step Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__THE_STEP_TABLE = STEP__THE_STEP_TABLE;

  /**
   * The feature id for the '<em><b>The Doc String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__THE_DOC_STRING = STEP__THE_DOC_STRING;

  /**
   * The number of structural features of the '<em>Then</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN_FEATURE_COUNT = STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.AndImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getAnd()
   * @generated
   */
  int AND = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__NAME = STEP__NAME;

  /**
   * The feature id for the '<em><b>The Step Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__THE_STEP_TABLE = STEP__THE_STEP_TABLE;

  /**
   * The feature id for the '<em><b>The Doc String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__THE_DOC_STRING = STEP__THE_DOC_STRING;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ButImpl <em>But</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.ButImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getBut()
   * @generated
   */
  int BUT = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUT__NAME = STEP__NAME;

  /**
   * The feature id for the '<em><b>The Step Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUT__THE_STEP_TABLE = STEP__THE_STEP_TABLE;

  /**
   * The feature id for the '<em><b>The Doc String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUT__THE_DOC_STRING = STEP__THE_DOC_STRING;

  /**
   * The number of structural features of the '<em>But</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUT_FEATURE_COUNT = STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.AsteriskImpl <em>Asterisk</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.AsteriskImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getAsterisk()
   * @generated
   */
  int ASTERISK = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASTERISK__NAME = STEP__NAME;

  /**
   * The feature id for the '<em><b>The Step Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASTERISK__THE_STEP_TABLE = STEP__THE_STEP_TABLE;

  /**
   * The feature id for the '<em><b>The Doc String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASTERISK__THE_DOC_STRING = STEP__THE_DOC_STRING;

  /**
   * The number of structural features of the '<em>Asterisk</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASTERISK_FEATURE_COUNT = STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.StatementImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 23;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.TagImpl <em>Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.TagImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getTag()
   * @generated
   */
  int TAG = 24;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG__NAME = 0;

  /**
   * The number of structural features of the '<em>Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.cucumber.cucumber.impl.LineImpl <em>Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.cucumber.cucumber.impl.LineImpl
   * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getLine()
   * @generated
   */
  int LINE = 25;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE__NAME = 0;

  /**
   * The number of structural features of the '<em>Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.cucumber.cucumber.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.StepObject <em>Step Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step Object</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepObject
   * @generated
   */
  EClass getStepObject();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.StepObject#getStepDefinitions <em>Step Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Step Definitions</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepObject#getStepDefinitions()
   * @see #getStepObject()
   * @generated
   */
  EReference getStepObject_StepDefinitions();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.StepDefinition <em>Step Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step Definition</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepDefinition
   * @generated
   */
  EClass getStepDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.cucumber.cucumber.StepDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepDefinition#getName()
   * @see #getStepDefinition()
   * @generated
   */
  EAttribute getStepDefinition_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.StepDefinition#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepDefinition#getStatements()
   * @see #getStepDefinition()
   * @generated
   */
  EReference getStepDefinition_Statements();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.StepDefinition#getStepParameters <em>Step Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Step Parameters</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepDefinition#getStepParameters()
   * @see #getStepDefinition()
   * @generated
   */
  EReference getStepDefinition_StepParameters();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.StepParameters <em>Step Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step Parameters</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepParameters
   * @generated
   */
  EClass getStepParameters();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.cucumber.cucumber.StepParameters#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepParameters#getName()
   * @see #getStepParameters()
   * @generated
   */
  EAttribute getStepParameters_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.StepParameters#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepParameters#getStatements()
   * @see #getStepParameters()
   * @generated
   */
  EReference getStepParameters_Statements();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.cucumber.cucumber.StepParameters#getParametersTable <em>Parameters Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameters Table</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepParameters#getParametersTable()
   * @see #getStepParameters()
   * @generated
   */
  EReference getStepParameters_ParametersTable();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.ParametersTable <em>Parameters Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameters Table</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.ParametersTable
   * @generated
   */
  EClass getParametersTable();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.ParametersTable#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rows</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.ParametersTable#getRows()
   * @see #getParametersTable()
   * @generated
   */
  EReference getParametersTable_Rows();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.Feature#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tags</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Feature#getTags()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Tags();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.Feature#getAbstractScenarios <em>Abstract Scenarios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Abstract Scenarios</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Feature#getAbstractScenarios()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_AbstractScenarios();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.AbstractScenario <em>Abstract Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Scenario</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.AbstractScenario
   * @generated
   */
  EClass getAbstractScenario();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.cucumber.cucumber.AbstractScenario#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.AbstractScenario#getName()
   * @see #getAbstractScenario()
   * @generated
   */
  EAttribute getAbstractScenario_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.AbstractScenario#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.AbstractScenario#getStatements()
   * @see #getAbstractScenario()
   * @generated
   */
  EReference getAbstractScenario_Statements();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.AbstractScenario#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.AbstractScenario#getSteps()
   * @see #getAbstractScenario()
   * @generated
   */
  EReference getAbstractScenario_Steps();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Background <em>Background</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Background</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Background
   * @generated
   */
  EClass getBackground();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Scenario <em>Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Scenario
   * @generated
   */
  EClass getScenario();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.Scenario#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tags</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Scenario#getTags()
   * @see #getScenario()
   * @generated
   */
  EReference getScenario_Tags();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.ScenarioOutline <em>Scenario Outline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario Outline</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.ScenarioOutline
   * @generated
   */
  EClass getScenarioOutline();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.ScenarioOutline#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tags</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.ScenarioOutline#getTags()
   * @see #getScenarioOutline()
   * @generated
   */
  EReference getScenarioOutline_Tags();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.ScenarioOutline#getExamples <em>Examples</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Examples</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.ScenarioOutline#getExamples()
   * @see #getScenarioOutline()
   * @generated
   */
  EReference getScenarioOutline_Examples();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Examples <em>Examples</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Examples</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Examples
   * @generated
   */
  EClass getExamples();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.Examples#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tags</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Examples#getTags()
   * @see #getExamples()
   * @generated
   */
  EReference getExamples_Tags();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.cucumber.cucumber.Examples#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Examples#getName()
   * @see #getExamples()
   * @generated
   */
  EAttribute getExamples_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.Examples#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Examples#getStatements()
   * @see #getExamples()
   * @generated
   */
  EReference getExamples_Statements();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.cucumber.cucumber.Examples#getTheExamplesTable <em>The Examples Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>The Examples Table</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Examples#getTheExamplesTable()
   * @see #getExamples()
   * @generated
   */
  EReference getExamples_TheExamplesTable();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.ExamplesTable <em>Examples Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Examples Table</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.ExamplesTable
   * @generated
   */
  EClass getExamplesTable();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.ExamplesTable#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rows</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.ExamplesTable#getRows()
   * @see #getExamplesTable()
   * @generated
   */
  EReference getExamplesTable_Rows();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.StepTable <em>Step Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step Table</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepTable
   * @generated
   */
  EClass getStepTable();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.StepTable#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rows</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.StepTable#getRows()
   * @see #getStepTable()
   * @generated
   */
  EReference getStepTable_Rows();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Row <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Row
   * @generated
   */
  EClass getRow();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.Row#getCells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cells</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Row#getCells()
   * @see #getRow()
   * @generated
   */
  EReference getRow_Cells();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Cell
   * @generated
   */
  EClass getCell();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.cucumber.cucumber.Cell#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Cell#getName()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_Name();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Step
   * @generated
   */
  EClass getStep();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.cucumber.cucumber.Step#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Step#getName()
   * @see #getStep()
   * @generated
   */
  EAttribute getStep_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.cucumber.cucumber.Step#getTheStepTable <em>The Step Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>The Step Table</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Step#getTheStepTable()
   * @see #getStep()
   * @generated
   */
  EReference getStep_TheStepTable();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.cucumber.cucumber.Step#getTheDocString <em>The Doc String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>The Doc String</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Step#getTheDocString()
   * @see #getStep()
   * @generated
   */
  EReference getStep_TheDocString();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.DocString <em>Doc String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Doc String</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.DocString
   * @generated
   */
  EClass getDocString();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.cucumber.cucumber.DocString#getLines <em>Lines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lines</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.DocString#getLines()
   * @see #getDocString()
   * @generated
   */
  EReference getDocString_Lines();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Given <em>Given</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Given</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Given
   * @generated
   */
  EClass getGiven();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.When <em>When</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>When</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.When
   * @generated
   */
  EClass getWhen();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Then <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Then</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Then
   * @generated
   */
  EClass getThen();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.But <em>But</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>But</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.But
   * @generated
   */
  EClass getBut();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Asterisk <em>Asterisk</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asterisk</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Asterisk
   * @generated
   */
  EClass getAsterisk();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.cucumber.cucumber.Statement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Statement#getName()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Name();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Tag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tag</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Tag
   * @generated
   */
  EClass getTag();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.cucumber.cucumber.Tag#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Tag#getName()
   * @see #getTag()
   * @generated
   */
  EAttribute getTag_Name();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.cucumber.cucumber.Line <em>Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Line</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Line
   * @generated
   */
  EClass getLine();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.cucumber.cucumber.Line#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.cucumber.cucumber.Line#getName()
   * @see #getLine()
   * @generated
   */
  EAttribute getLine_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CucumberFactory getCucumberFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.ModelImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StepObjectImpl <em>Step Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.StepObjectImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStepObject()
     * @generated
     */
    EClass STEP_OBJECT = eINSTANCE.getStepObject();

    /**
     * The meta object literal for the '<em><b>Step Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_OBJECT__STEP_DEFINITIONS = eINSTANCE.getStepObject_StepDefinitions();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StepDefinitionImpl <em>Step Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.StepDefinitionImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStepDefinition()
     * @generated
     */
    EClass STEP_DEFINITION = eINSTANCE.getStepDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP_DEFINITION__NAME = eINSTANCE.getStepDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_DEFINITION__STATEMENTS = eINSTANCE.getStepDefinition_Statements();

    /**
     * The meta object literal for the '<em><b>Step Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_DEFINITION__STEP_PARAMETERS = eINSTANCE.getStepDefinition_StepParameters();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StepParametersImpl <em>Step Parameters</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.StepParametersImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStepParameters()
     * @generated
     */
    EClass STEP_PARAMETERS = eINSTANCE.getStepParameters();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP_PARAMETERS__NAME = eINSTANCE.getStepParameters_Name();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_PARAMETERS__STATEMENTS = eINSTANCE.getStepParameters_Statements();

    /**
     * The meta object literal for the '<em><b>Parameters Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_PARAMETERS__PARAMETERS_TABLE = eINSTANCE.getStepParameters_ParametersTable();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ParametersTableImpl <em>Parameters Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.ParametersTableImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getParametersTable()
     * @generated
     */
    EClass PARAMETERS_TABLE = eINSTANCE.getParametersTable();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETERS_TABLE__ROWS = eINSTANCE.getParametersTable_Rows();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.FeatureImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__TAGS = eINSTANCE.getFeature_Tags();

    /**
     * The meta object literal for the '<em><b>Abstract Scenarios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__ABSTRACT_SCENARIOS = eINSTANCE.getFeature_AbstractScenarios();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.AbstractScenarioImpl <em>Abstract Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.AbstractScenarioImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getAbstractScenario()
     * @generated
     */
    EClass ABSTRACT_SCENARIO = eINSTANCE.getAbstractScenario();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_SCENARIO__NAME = eINSTANCE.getAbstractScenario_Name();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_SCENARIO__STATEMENTS = eINSTANCE.getAbstractScenario_Statements();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_SCENARIO__STEPS = eINSTANCE.getAbstractScenario_Steps();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.BackgroundImpl <em>Background</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.BackgroundImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getBackground()
     * @generated
     */
    EClass BACKGROUND = eINSTANCE.getBackground();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ScenarioImpl <em>Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.ScenarioImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getScenario()
     * @generated
     */
    EClass SCENARIO = eINSTANCE.getScenario();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO__TAGS = eINSTANCE.getScenario_Tags();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ScenarioOutlineImpl <em>Scenario Outline</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.ScenarioOutlineImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getScenarioOutline()
     * @generated
     */
    EClass SCENARIO_OUTLINE = eINSTANCE.getScenarioOutline();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO_OUTLINE__TAGS = eINSTANCE.getScenarioOutline_Tags();

    /**
     * The meta object literal for the '<em><b>Examples</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO_OUTLINE__EXAMPLES = eINSTANCE.getScenarioOutline_Examples();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ExamplesImpl <em>Examples</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.ExamplesImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getExamples()
     * @generated
     */
    EClass EXAMPLES = eINSTANCE.getExamples();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXAMPLES__TAGS = eINSTANCE.getExamples_Tags();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXAMPLES__NAME = eINSTANCE.getExamples_Name();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXAMPLES__STATEMENTS = eINSTANCE.getExamples_Statements();

    /**
     * The meta object literal for the '<em><b>The Examples Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXAMPLES__THE_EXAMPLES_TABLE = eINSTANCE.getExamples_TheExamplesTable();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ExamplesTableImpl <em>Examples Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.ExamplesTableImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getExamplesTable()
     * @generated
     */
    EClass EXAMPLES_TABLE = eINSTANCE.getExamplesTable();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXAMPLES_TABLE__ROWS = eINSTANCE.getExamplesTable_Rows();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StepTableImpl <em>Step Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.StepTableImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStepTable()
     * @generated
     */
    EClass STEP_TABLE = eINSTANCE.getStepTable();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_TABLE__ROWS = eINSTANCE.getStepTable_Rows();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.RowImpl <em>Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.RowImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getRow()
     * @generated
     */
    EClass ROW = eINSTANCE.getRow();

    /**
     * The meta object literal for the '<em><b>Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW__CELLS = eINSTANCE.getRow_Cells();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.CellImpl <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.CellImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getCell()
     * @generated
     */
    EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__NAME = eINSTANCE.getCell_Name();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StepImpl <em>Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.StepImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStep()
     * @generated
     */
    EClass STEP = eINSTANCE.getStep();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP__NAME = eINSTANCE.getStep_Name();

    /**
     * The meta object literal for the '<em><b>The Step Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__THE_STEP_TABLE = eINSTANCE.getStep_TheStepTable();

    /**
     * The meta object literal for the '<em><b>The Doc String</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__THE_DOC_STRING = eINSTANCE.getStep_TheDocString();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.DocStringImpl <em>Doc String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.DocStringImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getDocString()
     * @generated
     */
    EClass DOC_STRING = eINSTANCE.getDocString();

    /**
     * The meta object literal for the '<em><b>Lines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOC_STRING__LINES = eINSTANCE.getDocString_Lines();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.GivenImpl <em>Given</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.GivenImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getGiven()
     * @generated
     */
    EClass GIVEN = eINSTANCE.getGiven();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.WhenImpl <em>When</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.WhenImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getWhen()
     * @generated
     */
    EClass WHEN = eINSTANCE.getWhen();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ThenImpl <em>Then</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.ThenImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getThen()
     * @generated
     */
    EClass THEN = eINSTANCE.getThen();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.AndImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.ButImpl <em>But</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.ButImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getBut()
     * @generated
     */
    EClass BUT = eINSTANCE.getBut();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.AsteriskImpl <em>Asterisk</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.AsteriskImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getAsterisk()
     * @generated
     */
    EClass ASTERISK = eINSTANCE.getAsterisk();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.StatementImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__NAME = eINSTANCE.getStatement_Name();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.TagImpl <em>Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.TagImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getTag()
     * @generated
     */
    EClass TAG = eINSTANCE.getTag();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAG__NAME = eINSTANCE.getTag_Name();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.cucumber.cucumber.impl.LineImpl <em>Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.cucumber.cucumber.impl.LineImpl
     * @see org.farhan.dsl.cucumber.cucumber.impl.CucumberPackageImpl#getLine()
     * @generated
     */
    EClass LINE = eINSTANCE.getLine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE__NAME = eINSTANCE.getLine_Name();

  }

} //CucumberPackage
