/**
 * generated by Xtext 2.39.0.M1
 */
package org.farhan.dsl.sheepdog.sheepDog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Setup</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.farhan.dsl.sheepdog.sheepDog.SheepDogPackage#getTestSetup()
 * @model
 * @generated
 */
public interface TestSetup extends TestStepContainer
{
} // TestSetup
