/**
 * generated by Xtext 2.32.0
 */
package org.farhan.cukefsm.cucumberFSM;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Row Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.cukefsm.cucumberFSM.RowCell#getCell <em>Cell</em>}</li>
 * </ul>
 *
 * @see org.farhan.cukefsm.cucumberFSM.CucumberFSMPackage#getRowCell()
 * @model
 * @generated
 */
public interface RowCell extends EObject
{
  /**
   * Returns the value of the '<em><b>Cell</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell</em>' attribute.
   * @see #setCell(String)
   * @see org.farhan.cukefsm.cucumberFSM.CucumberFSMPackage#getRowCell_Cell()
   * @model
   * @generated
   */
  String getCell();

  /**
   * Sets the value of the '{@link org.farhan.cukefsm.cucumberFSM.RowCell#getCell <em>Cell</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cell</em>' attribute.
   * @see #getCell()
   * @generated
   */
  void setCell(String value);

} // RowCell
