/*
 * generated by Xtext 2.32.0
 */
package org.farhan.dsl.cucumber.tests.parsing;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.farhan.dsl.cucumber.tests.CucumberInjectorProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(CucumberInjectorProvider.class)
public class ScenarioParsingTest extends ParsingTest {

	@Test
	public void parseScenarioWithName() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("Feature: This is a test feature\n");
		sb.append("Scenario: Submit a claim\n");
		assertNoFeatureErrors(sb);
	}

	@Test
	public void parseScenarioWithoutName() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("Feature: This is a test feature\n");
		sb.append("Scenario:");
		assertFeatureErrors(sb);
	}

	@Test
	public void parseScenarioWithoutNameEOL() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("Feature: This is a test feature\n");
		sb.append("Scenario: Submit a claim");
		assertFeatureErrors(sb);
	}

	@Test
	public void parseScenarioWithTags() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("Feature: This is a test feature\n");
		sb.append("@tag1\n");
		sb.append("Scenario: Submit a claim\n");
		assertNoFeatureErrors(sb);
	}

	@Test
	public void parseScenarioWithDescription() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("Feature: This is a test feature\n");
		sb.append("Scenario: Submit a claim\n");
		sb.append("Basic EDI claim\n");
		assertNoFeatureErrors(sb);
	}

	@Test
	public void parseScenarioWithMultilineDescription() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("Feature: This is a test feature\n");
		sb.append("Scenario: Submit a claim\n");
		sb.append("Basic EDI claim\n");
		sb.append("No deductible\n");
		assertNoFeatureErrors(sb);
	}

	@Test
	public void parseScenarioWithoutDescriptionEOL() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("Feature: This is a test feature\n");
		sb.append("Scenario: Submit a claim\n");
		sb.append("Basic EDI claim");
		assertFeatureErrors(sb);
	}

	@Test
	public void parseScenarioWithSteps() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("Feature: This is a test feature\n");
		sb.append("Scenario: Submit a claim\n");
		sb.append("Given do step one\n");
		sb.append("When do step three\n");
		assertNoFeatureErrors(sb);
	}

	@Test
	public void parseScenarioWithEverything() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("Feature: This is a test feature\n");
		sb.append("@tag1\n");
		sb.append("Scenario: Submit a claim\n");
		sb.append("Basic EDI claim\n");
		sb.append("No deductible\n");
		sb.append("Given do step one\n");
		sb.append("When do step three\n");
		assertNoFeatureErrors(sb);
	}
}
