/**
 * generated by Xtext 2.32.0
 */
package mbt.cucumber;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Col</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mbt.cucumber.TableCol#getCell <em>Cell</em>}</li>
 * </ul>
 *
 * @see mbt.cucumber.CucumberPackage#getTableCol()
 * @model
 * @generated
 */
public interface TableCol extends EObject
{
  /**
   * Returns the value of the '<em><b>Cell</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell</em>' attribute.
   * @see #setCell(String)
   * @see mbt.cucumber.CucumberPackage#getTableCol_Cell()
   * @model
   * @generated
   */
  String getCell();

  /**
   * Sets the value of the '{@link mbt.cucumber.TableCol#getCell <em>Cell</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cell</em>' attribute.
   * @see #getCell()
   * @generated
   */
  void setCell(String value);

} // TableCol
