/**
 * generated by Xtext 2.37.0
 */
package org.farhan.mbt.sheepDog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.farhan.mbt.sheepDog.SheepDogPackage#getAnd()
 * @model
 * @generated
 */
public interface And extends Step
{
} // And
