/**
 * generated by Xtext 2.35.0
 */
package org.farhan.cucumber;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Asterisk</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.farhan.cucumber.CucumberPackage#getAsterisk()
 * @model
 * @generated
 */
public interface Asterisk extends Step
{
} // Asterisk
