/**
 * generated by Xtext 2.32.0
 */
package org.farhan.cucumber;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.farhan.cucumber.CucumberFactory
 * @model kind="package"
 * @generated
 */
public interface CucumberPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cucumber";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.farhan.org/Cucumber";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cucumber";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CucumberPackage eINSTANCE = org.farhan.cucumber.impl.CucumberPackageImpl.init();

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.FeatureImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__TITLE = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Background</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__BACKGROUND = 2;

  /**
   * The feature id for the '<em><b>Scenarios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__SCENARIOS = 3;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.BackgroundImpl <em>Background</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.BackgroundImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getBackground()
   * @generated
   */
  int BACKGROUND = 1;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND__TITLE = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND__STEPS = 2;

  /**
   * The number of structural features of the '<em>Background</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.AbstractScenarioImpl <em>Abstract Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.AbstractScenarioImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getAbstractScenario()
   * @generated
   */
  int ABSTRACT_SCENARIO = 2;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_SCENARIO__TITLE = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_SCENARIO__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_SCENARIO__STEPS = 2;

  /**
   * The number of structural features of the '<em>Abstract Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_SCENARIO_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.ScenarioImpl <em>Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.ScenarioImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getScenario()
   * @generated
   */
  int SCENARIO = 3;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__TITLE = ABSTRACT_SCENARIO__TITLE;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__DESCRIPTION = ABSTRACT_SCENARIO__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__STEPS = ABSTRACT_SCENARIO__STEPS;

  /**
   * The number of structural features of the '<em>Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_FEATURE_COUNT = ABSTRACT_SCENARIO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.ScenarioOutlineImpl <em>Scenario Outline</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.ScenarioOutlineImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getScenarioOutline()
   * @generated
   */
  int SCENARIO_OUTLINE = 4;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE__TITLE = ABSTRACT_SCENARIO__TITLE;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE__DESCRIPTION = ABSTRACT_SCENARIO__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE__STEPS = ABSTRACT_SCENARIO__STEPS;

  /**
   * The feature id for the '<em><b>Examples</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE__EXAMPLES = ABSTRACT_SCENARIO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Scenario Outline</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE_FEATURE_COUNT = ABSTRACT_SCENARIO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.ExampleImpl <em>Example</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.ExampleImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getExample()
   * @generated
   */
  int EXAMPLE = 5;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLE__TITLE = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLE__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLE__TABLE = 2;

  /**
   * The number of structural features of the '<em>Example</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.StepImpl <em>Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.StepImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getStep()
   * @generated
   */
  int STEP = 6;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__TITLE = 0;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__TABLE = 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__TEXT = 2;

  /**
   * The number of structural features of the '<em>Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.TableImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getTable()
   * @generated
   */
  int TABLE = 7;

  /**
   * The feature id for the '<em><b>Rows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__ROWS = 0;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.TableRowImpl <em>Table Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.TableRowImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getTableRow()
   * @generated
   */
  int TABLE_ROW = 8;

  /**
   * The feature id for the '<em><b>Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ROW__CELLS = 0;

  /**
   * The number of structural features of the '<em>Table Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ROW_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.RowCellImpl <em>Row Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.RowCellImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getRowCell()
   * @generated
   */
  int ROW_CELL = 9;

  /**
   * The feature id for the '<em><b>Cell</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_CELL__CELL = 0;

  /**
   * The number of structural features of the '<em>Row Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_CELL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.DocStringImpl <em>Doc String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.DocStringImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getDocString()
   * @generated
   */
  int DOC_STRING = 10;

  /**
   * The number of structural features of the '<em>Doc String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOC_STRING_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.farhan.cucumber.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.cucumber.impl.DescriptionImpl
   * @see org.farhan.cucumber.impl.CucumberPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 11;

  /**
   * The feature id for the '<em><b>Sentences</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__SENTENCES = 0;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see org.farhan.cucumber.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.cucumber.Feature#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.farhan.cucumber.Feature#getTitle()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.cucumber.Feature#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.farhan.cucumber.Feature#getDescription()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.cucumber.Feature#getBackground <em>Background</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Background</em>'.
   * @see org.farhan.cucumber.Feature#getBackground()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Background();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.cucumber.Feature#getScenarios <em>Scenarios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scenarios</em>'.
   * @see org.farhan.cucumber.Feature#getScenarios()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Scenarios();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.Background <em>Background</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Background</em>'.
   * @see org.farhan.cucumber.Background
   * @generated
   */
  EClass getBackground();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.cucumber.Background#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.farhan.cucumber.Background#getTitle()
   * @see #getBackground()
   * @generated
   */
  EAttribute getBackground_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.cucumber.Background#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.farhan.cucumber.Background#getDescription()
   * @see #getBackground()
   * @generated
   */
  EReference getBackground_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.cucumber.Background#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see org.farhan.cucumber.Background#getSteps()
   * @see #getBackground()
   * @generated
   */
  EReference getBackground_Steps();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.AbstractScenario <em>Abstract Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Scenario</em>'.
   * @see org.farhan.cucumber.AbstractScenario
   * @generated
   */
  EClass getAbstractScenario();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.cucumber.AbstractScenario#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.farhan.cucumber.AbstractScenario#getTitle()
   * @see #getAbstractScenario()
   * @generated
   */
  EAttribute getAbstractScenario_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.cucumber.AbstractScenario#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.farhan.cucumber.AbstractScenario#getDescription()
   * @see #getAbstractScenario()
   * @generated
   */
  EReference getAbstractScenario_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.cucumber.AbstractScenario#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see org.farhan.cucumber.AbstractScenario#getSteps()
   * @see #getAbstractScenario()
   * @generated
   */
  EReference getAbstractScenario_Steps();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.Scenario <em>Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario</em>'.
   * @see org.farhan.cucumber.Scenario
   * @generated
   */
  EClass getScenario();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.ScenarioOutline <em>Scenario Outline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario Outline</em>'.
   * @see org.farhan.cucumber.ScenarioOutline
   * @generated
   */
  EClass getScenarioOutline();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.cucumber.ScenarioOutline#getExamples <em>Examples</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Examples</em>'.
   * @see org.farhan.cucumber.ScenarioOutline#getExamples()
   * @see #getScenarioOutline()
   * @generated
   */
  EReference getScenarioOutline_Examples();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.Example <em>Example</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Example</em>'.
   * @see org.farhan.cucumber.Example
   * @generated
   */
  EClass getExample();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.cucumber.Example#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.farhan.cucumber.Example#getTitle()
   * @see #getExample()
   * @generated
   */
  EAttribute getExample_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.cucumber.Example#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.farhan.cucumber.Example#getDescription()
   * @see #getExample()
   * @generated
   */
  EReference getExample_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.cucumber.Example#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Table</em>'.
   * @see org.farhan.cucumber.Example#getTable()
   * @see #getExample()
   * @generated
   */
  EReference getExample_Table();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step</em>'.
   * @see org.farhan.cucumber.Step
   * @generated
   */
  EClass getStep();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.cucumber.Step#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.farhan.cucumber.Step#getTitle()
   * @see #getStep()
   * @generated
   */
  EAttribute getStep_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.cucumber.Step#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Table</em>'.
   * @see org.farhan.cucumber.Step#getTable()
   * @see #getStep()
   * @generated
   */
  EReference getStep_Table();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.cucumber.Step#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.farhan.cucumber.Step#getText()
   * @see #getStep()
   * @generated
   */
  EReference getStep_Text();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see org.farhan.cucumber.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.cucumber.Table#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rows</em>'.
   * @see org.farhan.cucumber.Table#getRows()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Rows();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.TableRow <em>Table Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Row</em>'.
   * @see org.farhan.cucumber.TableRow
   * @generated
   */
  EClass getTableRow();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.cucumber.TableRow#getCells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cells</em>'.
   * @see org.farhan.cucumber.TableRow#getCells()
   * @see #getTableRow()
   * @generated
   */
  EReference getTableRow_Cells();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.RowCell <em>Row Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Cell</em>'.
   * @see org.farhan.cucumber.RowCell
   * @generated
   */
  EClass getRowCell();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.cucumber.RowCell#getCell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cell</em>'.
   * @see org.farhan.cucumber.RowCell#getCell()
   * @see #getRowCell()
   * @generated
   */
  EAttribute getRowCell_Cell();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.DocString <em>Doc String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Doc String</em>'.
   * @see org.farhan.cucumber.DocString
   * @generated
   */
  EClass getDocString();

  /**
   * Returns the meta object for class '{@link org.farhan.cucumber.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see org.farhan.cucumber.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the attribute list '{@link org.farhan.cucumber.Description#getSentences <em>Sentences</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Sentences</em>'.
   * @see org.farhan.cucumber.Description#getSentences()
   * @see #getDescription()
   * @generated
   */
  EAttribute getDescription_Sentences();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CucumberFactory getCucumberFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.FeatureImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__TITLE = eINSTANCE.getFeature_Title();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__DESCRIPTION = eINSTANCE.getFeature_Description();

    /**
     * The meta object literal for the '<em><b>Background</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__BACKGROUND = eINSTANCE.getFeature_Background();

    /**
     * The meta object literal for the '<em><b>Scenarios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__SCENARIOS = eINSTANCE.getFeature_Scenarios();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.BackgroundImpl <em>Background</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.BackgroundImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getBackground()
     * @generated
     */
    EClass BACKGROUND = eINSTANCE.getBackground();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BACKGROUND__TITLE = eINSTANCE.getBackground_Title();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BACKGROUND__DESCRIPTION = eINSTANCE.getBackground_Description();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BACKGROUND__STEPS = eINSTANCE.getBackground_Steps();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.AbstractScenarioImpl <em>Abstract Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.AbstractScenarioImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getAbstractScenario()
     * @generated
     */
    EClass ABSTRACT_SCENARIO = eINSTANCE.getAbstractScenario();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_SCENARIO__TITLE = eINSTANCE.getAbstractScenario_Title();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_SCENARIO__DESCRIPTION = eINSTANCE.getAbstractScenario_Description();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_SCENARIO__STEPS = eINSTANCE.getAbstractScenario_Steps();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.ScenarioImpl <em>Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.ScenarioImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getScenario()
     * @generated
     */
    EClass SCENARIO = eINSTANCE.getScenario();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.ScenarioOutlineImpl <em>Scenario Outline</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.ScenarioOutlineImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getScenarioOutline()
     * @generated
     */
    EClass SCENARIO_OUTLINE = eINSTANCE.getScenarioOutline();

    /**
     * The meta object literal for the '<em><b>Examples</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO_OUTLINE__EXAMPLES = eINSTANCE.getScenarioOutline_Examples();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.ExampleImpl <em>Example</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.ExampleImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getExample()
     * @generated
     */
    EClass EXAMPLE = eINSTANCE.getExample();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXAMPLE__TITLE = eINSTANCE.getExample_Title();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXAMPLE__DESCRIPTION = eINSTANCE.getExample_Description();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXAMPLE__TABLE = eINSTANCE.getExample_Table();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.StepImpl <em>Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.StepImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getStep()
     * @generated
     */
    EClass STEP = eINSTANCE.getStep();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP__TITLE = eINSTANCE.getStep_Title();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__TABLE = eINSTANCE.getStep_Table();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__TEXT = eINSTANCE.getStep_Text();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.TableImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__ROWS = eINSTANCE.getTable_Rows();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.TableRowImpl <em>Table Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.TableRowImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getTableRow()
     * @generated
     */
    EClass TABLE_ROW = eINSTANCE.getTableRow();

    /**
     * The meta object literal for the '<em><b>Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_ROW__CELLS = eINSTANCE.getTableRow_Cells();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.RowCellImpl <em>Row Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.RowCellImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getRowCell()
     * @generated
     */
    EClass ROW_CELL = eINSTANCE.getRowCell();

    /**
     * The meta object literal for the '<em><b>Cell</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROW_CELL__CELL = eINSTANCE.getRowCell_Cell();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.DocStringImpl <em>Doc String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.DocStringImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getDocString()
     * @generated
     */
    EClass DOC_STRING = eINSTANCE.getDocString();

    /**
     * The meta object literal for the '{@link org.farhan.cucumber.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.cucumber.impl.DescriptionImpl
     * @see org.farhan.cucumber.impl.CucumberPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Sentences</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION__SENTENCES = eINSTANCE.getDescription_Sentences();

  }

} //CucumberPackage
