/**
 * generated by Xtext 2.32.0
 */
package org.farhan.cucumber;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.cucumber.StepObject#getStepDefinitions <em>Step Definitions</em>}</li>
 * </ul>
 *
 * @see org.farhan.cucumber.CucumberPackage#getStepObject()
 * @model
 * @generated
 */
public interface StepObject extends Model
{
  /**
   * Returns the value of the '<em><b>Step Definitions</b></em>' containment reference list.
   * The list contents are of type {@link org.farhan.cucumber.StepDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step Definitions</em>' containment reference list.
   * @see org.farhan.cucumber.CucumberPackage#getStepObject_StepDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<StepDefinition> getStepDefinitions();

} // StepObject
