/**
 * generated by Xtext 2.36.0
 */
package org.farhan.mbt.cucumber;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>But</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.farhan.mbt.cucumber.CucumberPackage#getBut()
 * @model
 * @generated
 */
public interface But extends Step
{
} // But
