name: Publish Sheep Dog Xtext Cucumber Release

on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-xtext-cuke-plugin:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheepdogxtextcukeplugin.parent'
      plugin: 'Sheep'
    secrets: inherit

  sheep-dog-dev:
    needs: [sheep-dog-xtext-cuke-plugin]
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev'
      plugin: 'Maven'
    secrets: inherit

  sheep-dog-dev-maven-plugin:
    needs: [sheep-dog-dev]
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-maven-plugin'
      plugin: 'Maven'
    secrets: inherit    

  sheep-dog-dev-svc:
    needs: [sheep-dog-dev]
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-svc'
      plugin: 'Maven'
    secrets: inherit
  
  sheep-dog-dev-svc-maven-plugin:
    needs: [sheep-dog-dev-svc]
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-svc-maven-plugin'
      plugin: 'Maven'
    secrets: inherit            
    
  merge-into-develop:
    needs: [deploy-to-minikube]
    uses: ./.github/workflows/merge.yml
    with:
      source: 'main'
      target: 'develop'
    secrets: inherit      