name: Publish Sheep Dog Dev Service Release

on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-dev-svc:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-svc'
      plugin: 'Maven'
    secrets: inherit

  sheep-dog-dev-svc-maven-plugin:
    needs: [sheep-dog-dev-svc]
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-svc-maven-plugin'
      plugin: 'Maven'
    secrets: inherit   
         
  merge-into-develop:
    needs: [deploy-to-minikube]
    uses: ./.github/workflows/merge.yml
    with:
      source: 'main'
      target: 'develop'
    secrets: inherit  