name: Snapshot

on:
  workflow_call:
    inputs:
      project:
        description: 'Project'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
        type: choice
        options:
          - sheep-dog-mgmt-maven-plugin
          - sheep-dog-dev
          - sheep-dog-dev-maven-plugin
          - sheep-dog-test
          - sheepdogcucumber.parent
          - sheepdogxtextplugin.parent
jobs:
  build:
    runs-on: [farhan5248-runners, windows]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.9'
    - name: Run Maven
      working-directory: ./${{ inputs.project }}
      run: |
        mvn -U deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
