name: Snapshot Docker

on:
  workflow_call:
    inputs:
      project:
        description: 'Project'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
        type: choice
        options:
          - sheep-dog-mgmt-maven-plugin
          - sheep-dog-dev
          - sheep-dog-dev-maven-plugin
          - sheep-dog-dev-svc
          - sheep-dog-dev-svc-maven-plugin
          - sheep-dog-test
          - sheepdogcucumber.parent
          - sheepdogxtextplugin.parent
jobs:
  build:
    runs-on: [farhan5248-runners, linux]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.9'
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Run Maven
      working-directory: ./${{ inputs.project }}
      run: |
        mvn -U deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ARTEMIS_USER: ${{ secrets.ARTEMIS_USER }}
        ARTEMIS_PASSWORD: ${{ secrets.ARTEMIS_PASSWORD }}