/**
 * generated by Xtext 2.36.0
 */
package org.farhan.cucumber.impl;

import org.eclipse.emf.ecore.EClass;

import org.farhan.cucumber.And;
import org.farhan.cucumber.CucumberPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>And</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AndImpl extends StepImpl implements And
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AndImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CucumberPackage.Literals.AND;
  }

} //AndImpl
